// <auto-generated />
namespace PPIS_Tajma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addstatustoticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstatustoticket));
        
        string IMigrationMetadata.Id
        {
            get { return "201503282240476_add status to ticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
