// <auto-generated />
namespace PPIS_Tajma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addchangestatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchangestatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201503282241386_add change status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
